=begin
#Carpool application API

#API for the Carpool application

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CarpoolEntryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CarpoolEntryApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CarpoolEntryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarpoolEntryApi' do
    it 'should create an instance of CarpoolEntryApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CarpoolEntryApi)
    end
  end

  # unit tests for api_carpool_entry_get
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_carpool_entry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_carpool_entry_id_delete
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_carpool_entry_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_carpool_entry_id_get
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_carpool_entry_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_carpool_entry_id_put
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [CarpoolEntry] :carpool_entry 
  # @return [nil]
  describe 'api_carpool_entry_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_carpool_entry_post
  # @param [Hash] opts the optional parameters
  # @option opts [CarpoolEntry] :carpool_entry 
  # @return [nil]
  describe 'api_carpool_entry_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
